[workspace]
resolver = "3"
members = ["day1", "day2", "day3", "day4", "day5"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
num-integer = "0.1"
predicates = "3.1.3"
